<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="257" started-at="2019-04-08T18:14:53Z" finished-at="2019-04-08T18:14:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="257" started-at="2019-04-08T18:14:53Z" finished-at="2019-04-08T18:14:54Z">
      <class name="testClasses.TestNG_EnableTimeOut">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testClasses.TestNG_EnableTimeOut@2344fc66]" name="setUp" is-config="true" duration-ms="16" started-at="2019-04-08T23:44:53Z" finished-at="2019-04-08T23:44:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testMethod1()[pri:0, instance:testClasses.TestNG_EnableTimeOut@2344fc66]" name="testMethod1" duration-ms="15" started-at="2019-04-08T23:44:53Z" finished-at="2019-04-08T23:44:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
        <test-method status="FAIL" signature="testMethod2()[pri:0, instance:testClasses.TestNG_EnableTimeOut@2344fc66]" name="testMethod2" duration-ms="187" started-at="2019-04-08T23:44:53Z" finished-at="2019-04-08T23:44:54Z">
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:289)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:246)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:667)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArrayIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod2 -->
        <test-method status="PASS" signature="CleanUp()[pri:0, instance:testClasses.TestNG_EnableTimeOut@2344fc66]" name="CleanUp" is-config="true" duration-ms="0" started-at="2019-04-08T23:44:54Z" finished-at="2019-04-08T23:44:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CleanUp -->
      </class> <!-- testClasses.TestNG_EnableTimeOut -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
